# Generated by Django 5.2.16 on 2026-07-30 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_department_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('priority', models.SmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('closed', '已关闭')], default='open', max_length=16, verbose_name='状态')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.department', verbose_name='归属部门')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
    ]
