# Generated by Django 5.2.16 on 2026-07-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=255, verbose_name='路径')),
                ('depth', models.SmallIntegerField(default=0, editable=False, verbose_name='层级')),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='权限码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('perm_type', models.CharField(choices=[('catalog', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=16, verbose_name='类型')),
                ('order_num', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('url_name', models.CharField(blank=True, max_length=128, verbose_name='URL name')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='图标')),
                ('is_visible', models.BooleanField(default=True, verbose_name='菜单可见')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_deprecated', models.BooleanField(default=False, verbose_name='已废弃')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='rbac.permission', verbose_name='上级')),
            ],
            options={
                'verbose_name': '权限点',
                'verbose_name_plural': '权限点',
                'ordering': ['path'],
                'abstract': False,
            },
        ),
    ]
