# Generated by Django 5.2.16 on 2026-07-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('data_scope', models.SmallIntegerField(choices=[(1, '全部数据'), (2, '本部门及以下'), (3, '仅本部门'), (4, '仅本人'), (5, '自定义部门')], default=4, verbose_name='数据范围')),
                ('order_num', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置角色不可删除', verbose_name='内置角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
