# Generated by Django 5.2.16 on 2026-07-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='inherits_from',
            field=models.ForeignKey(blank=True, help_text='本角色将自动拥有所选角色的全部权限', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inheritors', to='rbac.role', verbose_name='继承自'),
        ),
    ]
