# Generated by Django 5.2.16 on 2026-07-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_parent'),
        ('rbac', '0004_role_inherits_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_departments', to='accounts.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_departments', to='rbac.role')),
            ],
            options={
                'verbose_name': '角色数据范围部门',
                'verbose_name_plural': '角色数据范围部门',
                'unique_together': {('role', 'department')},
            },
        ),
    ]
