# Generated by Django 5.2.16 on 2026-08-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_roledepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, help_text='相对 frontend/src/pages/，不带扩展名，如 tickets/List', max_length=128, verbose_name='前端组件'),
        ),
        migrations.AddField(
            model_name='permission',
            name='route_path',
            field=models.CharField(blank=True, max_length=128, verbose_name='前端路由'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Django URL name'),
        ),
    ]
