# Generated by Django 5.2.16 on 2026-07-31 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=64, verbose_name='操作者名')),
                ('action', models.CharField(choices=[('login', '登录'), ('login_failed', '登录失败'), ('logout', '登出'), ('perm_denied', '访问被拒绝'), ('role.create', '创建角色'), ('role.update', '修改角色'), ('role.delete', '删除角色'), ('role.perm_set', '分配角色权限'), ('role.scope_set', '设置数据范围'), ('user.role_set', '分配用户角色'), ('user.create', '创建用户'), ('user.update', '修改用户'), ('user.delete', '删除用户')], db_index=True, max_length=64, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='目标ID')),
                ('target_repr', models.CharField(blank=True, max_length=128, verbose_name='目标描述')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='User-Agent')),
                ('result', models.CharField(choices=[('success', '成功'), ('failure', '失败')], default='success', max_length=16, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
